#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\InputOption;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Acacha AdminLTE Installer', '3.1.11');

// Add global Options to the Application
$app->getDefinition()->addOptions([
    new InputOption('--no-llum', '-L', InputOption::VALUE_NONE,
        'Does not use acacha/llum to install package. Llum does not use stubs to modify config/app.php file so your changes are respected. However llum use bash scripts that can be no compatible in all platforms'),
    new InputOption('--dev', '-d', InputOption::VALUE_NONE,
        'Installs the latest "development" release'),
    new InputOption('--use-vendor-publish', '-p', InputOption::VALUE_NONE,
        'Installs using php artisan vendor:publish --tag=adminlte --force . By default php artisan adminlte-laravel:publish is used'),
    new InputOption('--dontforce', '-F', InputOption::VALUE_NONE,
        'Ask before overwrite files during installation')]);

$app->add(new Acacha\AdminLTETemplateLaravel\Console\InstallCommand);
$app->add(new Acacha\AdminLTETemplateLaravel\Console\SocialCommand);

$app->run();
