#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Acacha AdminLTE Installer', '3.2.1');

$app->add(new Acacha\AdminLTETemplateLaravel\Console\InstallCommand);
$app->add(new Acacha\AdminLTETemplateLaravel\Console\SocialCommand);

$app->run();
